### ISSUE TITLE
Provide ability to show Managed Zones for a Project

### ISSUE THREAD

**Issue by dylan-tock** [terraform-google-modules/terraform-google-cloud-dns#17]
I am looking for a way to show the Managed Zones for a specific project.  The current functionality is great if I know the zone I'm working with, but does not provide discoverability for finding what zones are available.

My use case is as follows: I have a project that hosts multiple private Cloud DNS zones.  I have workflows that create new projects and would like those newly created projects to be able to be programmatically granted access to those private zones.  Ideally I would like functionality similar to what I get from `gcloud dns managed-zones list --project host-project`.

**Comment by dylan-tock** [comment]
This is still a thing that is desired.

**Comment by morgante** [comment]
It's not something we would plan to prioritize. Terraform is a tool for managing infrastructure as code, not for listing existing resources created outside of Terraform.

**Comment by dylan-tock** [comment]
@morgante, I believe your decision is reasonable to prevent scope creep, but a bit short sighted from an operational perspective.  Regardless, I shall respect your (and presumably the team's) decision.
