### ISSUE TITLE
DNS module support for force_destroy option

### ISSUE THREAD

**Issue by vponnam** [terraform-google-modules/terraform-google-cloud-dns#21]
Upstream resource [dns_managed_zone](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_managed_zone) supports `force_destroy`

Additional context on the requirement: https://github.com/hashicorp/terraform-provider-google/issues/1572

**Comment by morgante** [comment]
Are you managing `recordsets` outside the module?

**Comment by julien-sugg** [comment]
Hi, I'm also looking forward for the support of the `force_destroy` argument as most of the underlying records in the zone are dynamically generated in my clusters by `external-dns`. Hence, outside the scope of Terraform.
