### ISSUE TITLE
Labels is unsupported argument

### ISSUE THREAD

**Issue by ankiclockwise** [terraform-google-modules/terraform-google-cloud-dns#24]
i passed  
labels = {
    foo = "bar"
  }
It is unsupported argument. The readme file mentions the labels parameter.

**Comment by morgante** [comment]
Labels are supported here: https://github.com/terraform-google-modules/terraform-google-cloud-dns/blob/master/variables.tf#L71

Are you sure you're using this module? It's possible you have an old version.
