### ISSUE TITLE
module does not work in terraform 1.x "list" function deprecated

### ISSUE THREAD

**Issue by bizrad** [terraform-google-modules/terraform-google-cloud-dns#30]
When trying to use this module in the latest version of terraform it fails with the following error:

│ Error: Error in function call
│
│   on .terraform/modules/foo/main.tf line 105, in resource "google_dns_managed_zone" "public":
│  105:     for_each = var.dnssec_config == {} ? [] : list(var.dnssec_config)
│     ├────────────────
│     │ var.dnssec_config is object with 1 attribute "state"
│
│ Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ])
│ syntax to write a literal list.

**Comment by bharathkkb** [comment]
Hi @bizrad 
This has been fixed on main, unfortunately we haven't cut a new release yet due to https://github.com/terraform-google-modules/terraform-google-cloud-dns/pull/23#issuecomment-866179289
