### ISSUE TITLE
Can we add support for Cloud Logging while creating "public" Zone Type.  ?

### ISSUE THREAD

**Issue by hjdesai2** [terraform-google-modules/terraform-google-cloud-dns#35]
### Description

* Current GCP Environment supports enabling Cloud Logging via API / Console. However, it's not supported in Terraform Yet.
![Screen Shot 2022-02-11 at 1 20 23 PM](https://user-images.githubusercontent.com/5409373/153671883-4b9fbb1a-fd7b-42ca-91e8-1d8ccb9d75da.png)

### Terraform Resources

```markdown
Resource is present https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_managed_zone but I guess it's not even supported by provider.

Even Google API has a support for it https://cloud.google.com/dns/docs/reference/v1/managedZones
```

### Detailed design

```markdown
* Just need to add support for Cloud Logging Option
```

**Comment by hjdesai2** [comment]
Can we have some update on this ?

**Comment by hjdesai2** [comment]
@morgante @bharathkkb anything you can do. Just tagging you both as were active on previous issues. Thank you!

**Comment by zdunning13** [comment]
Would love to see this as an enhancement!
