### ISSUE TITLE
Clean repository history

### ISSUE THREAD

**Issue by lchastel** [terraform-google-modules/terraform-google-cloud-dns#61]
The repository is "big" due to binaries files that were added by mistake.

I used script git_find_big.sh from https://support.atlassian.com/bitbucket-cloud/docs/maintain-a-git-repository/#Manually-reviewing-large-files-in-your-repository

```
All sizes are in kB's. The pack column is the size of the object, compressed, inside the pack file.
size   pack   SHA                                       location
51098  13520  226ac64685d2a07ccd9672f7db5e3904971bc5aa  examples/private-zone/.terraform/plugins/linux_amd64/terraform-provider-google_v2.8.0_x4
19896  6544   4c05313dcd3e0fbb33cb89a766aed4a782085db0  examples/private-zone/.terraform/plugins/linux_amd64/terraform-provider-null_v2.1.2_x4
17586  6428   a6a43b82c87aba3df9ffaa0f3ab6b6d9ed31e82e  examples/private-zone/.terraform/plugins/linux_amd64/terraform-provider-google-beta_v2.8.0_x4
....
```

Could you please remove those files for history ?
When I have such operation to do, I use BFG (check the upper article for procedure)

PS : make a backup of the repository before doing the operation ;)

**Comment by tomwardill-payoneer** [comment]
This is still a problem. This module is over 26Mb on disk, which causes slow upload/download and is unnecessary.
