### ISSUE TITLE
Make DNS Record Attribute values optional

### ISSUE THREAD

**Issue by jeheyer** [terraform-google-modules/terraform-google-cloud-dns#78]
### TL;DR

It would be a time-saver at the parent module level to have some default values for DNS records.  Specifically, for those of us who can't remember what the default TTL is, make it optional with a default value of 5 minutes.  Also consider defaulting name to "" for wildcarding, and set record type to "A" since those would be the most common.  

### Terraform Resources

```markdown
google_dns_record_set
```

### Detailed design

```markdown
variable "recordsets" {
  type = list(object({
    name    = optional(string, "")
    type    = optinoal(string, "A")
    ttl     = optional(number, 300)
  }))
}
```

### Additional information

[https://github.com/aws2gcp/gcp-network-terraform/blob/main/dns/dns_records.tf](https://github.com/aws2gcp/gcp-network-terraform/blob/main/dns/dns_records.tf)

**Comment by jeheyer** [comment]
On a slightly related note, would be great if to fix a record type that's not in upper case:

```
type = upper(each.value.type)
```

**Comment by cloud-network-guy** [comment]
Baaaaaaaaam!   https://github.com/cloud-network-guy/terraform-google-dns/blob/main/main.tf
